name: Upload subdist

on:
  workflow_dispatch:
    inputs:
      run_id: 
        type: string
        required: true
      repo: 
        type: string
        required: true

permissions: write-all

jobs:
  upload-subdist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ghp_dist
          path: subdist
          repository: ${{ inputs.repo}}
          run-id: ${{ inputs.run_id }}
          github-token: ${{ secrets.GH_PAT }}

      - uses: actions/upload-pages-artifact@v3
        with:
          path: subdist

      - uses: actions/deploy-pages@v4
